### ISSUE TITLE
加入utf8编码格式定义

### ISSUE THREAD

**Issue by kalagxw** [garsonbb/sni-detecter#1]

**Comment by kalagxw** [comment]
SyntaxError: Non-ASCII character '\xe8' in file sni-detecter.py on line 48, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Python 2.7.12报错

建议输出格式不加时间 或可选
支持CIDR

**Comment by garsonbb** [comment]
哦，有时间就改改
