### ISSUE TITLE
完全不懂Python，琢磨半天能使用Python版了

### ISSUE THREAD

**Issue by rong2er** [garsonbb/sni-detecter#3]
不过好像这个扫描只是在你提供的task.txt里的102个当中扫描啊，怎么扫描未知的sni IP呢

**Comment by rong2er** [comment]
原来可以自己加IP段，但怎么筛选IP段，有什么讲究啊？

**Comment by garsonbb** [comment]
🤐 zoomeye是个好东西

**Comment by rong2er** [comment]
@garsonbb  说说方法好吗？搜索什么样的内容，我知道搜PCCW 什么的另外一个博主说过，但就那么几个

**Comment by garsonbb** [comment]
这个传播出去就不好了

**Comment by rong2er** [comment]
@garsonbb  那我们用你这个程序就无法施展搜索，现在那几个SNI 都是隔壁已经贴出来的用这个TASK.TXT来搜索也无意义。

**Comment by rong2er** [comment]
@garsonbb 你悄悄的告诉我方法吧！我每天都要来刷新这个网页好多遍看你有没有回复我-  -！不知道你何时再来。

**Comment by garsonbb** [comment]
你直接整个香港的IP段都扫一下就好了
